### ISSUE TITLE
I'm not seeing the correct return value for the example proof

### ISSUE THREAD

**Issue by patosullivan** [zorp-corp/verifier#1]
Ran this: `=vr -zkvm!prove-eden [41 [4 0 1]]`

I get "proof has been processed" eventually, but then `vr` produces `~`. It doesn't *look* like anything went wrong, though.

**Comment by ynx0** [comment]
So, the unit `~` is when there was in fact an error. I agree we could probably be more clear that that happened. We will put up a guide shortly on troubleshooting so that at the very least, we can help out better.

**Comment by patosullivan** [comment]
No problem! Looking forward to the guide.
